language: ruby
rvm:
  - 2.1.0
  - 2.1
  - 2.2
  - 2.3.0
before_install: gem update bundler # To use 1.10.0 or later. See: https://github.com/bundler/bundler/issues/3558
script: bundle exec rake
notifications:
  webhooks:
    - https://idobata.io/hook/6a98db40-ac68-45ec-a1b4-d8dd5851c2e3
