language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
before_install: gem update bundler # To use 1.10.0 or later. See: https://github.com/bundler/bundler/issues/3558
script: bundle exec rake
notifications:
  webhooks:
    - https://idobata.io/hook/6a98db40-ac68-45ec-a1b4-d8dd5851c2e3
